edited README for correct production and storyboard links
ucsb-cs156-w22/team02-w22-7pm-2 pull request #20
Opened 2022-02-02 21:43 UTC by tai-jui

# Overview

This PR needs to be approved  to trigger the GitHub
Action workflow that publishes the documentation to the QA site.

# Issues Addressed

If this PR closes or deals with issues, mention them and tag the issue number with the `#` syntax.

# Details

Where applicable, include "before" and "after" screenshots or animated GIFs.   The tool [LiceCAP](https://www.cockos.com/licecap/) or one of [these similar tools](https://www.nextofwindows.com/5-free-tools-to-screen-capture-to-gif-on-windows) 
can be used to capture screenshots/animated GIFs.

## Reminders (delete this section before merging or as code is merged)
- [ ] Explicitly link to this pull request each issue that it closes
- [ ] Assign one and ideally two reviewers to review this pull request. 
- [ ] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

2022-02-04 08:33 UTC, AHuangHe commented on README.md
> +- QA: <https://ucsb-cs156-w22.github.io/team02-w22-7pm-2docs-qa/>
A small mistake here (just missing a dash after 7pm-2)
should be https://github.com/ucsb-cs156-w22/team02-w22-7pm-2-docs-qa

2022-02-04 08:36 UTC, AHuangHe requested changes
There was a small mistake
Also, there's a conflict with the previous merge

2022-02-07 19:09 UTC, edisonnchen approved these changes
LGTM

2022-02-07 20:38 UTC, AHuangHe approved these changes
LGTM tho I am not sure why codecov is complaining

2022-02-07 21:30 UTC, merged