Rh del endpoint
ucsb-cs156-w22/team02-w22-7pm-2 pull request #36
Opened 2022-02-08 22:31 UTC by bobhe9606

# Overview

In a sentence or two, provide an overview of how this pull request updates the main branch.  You may use a bullet list if that helps.

# Issues Addressed

If this PR closes or deals with issues, mention them and tag the issue number with the `#` syntax.

# Details

Where applicable, include "before" and "after" screenshots or animated GIFs.   The tool [LiceCAP](https://www.cockos.com/licecap/) or one of [these similar tools](https://www.nextofwindows.com/5-free-tools-to-screen-capture-to-gif-on-windows) 
can be used to capture screenshots/animated GIFs.

## Reminders (delete this section before merging or as code is merged)
- [ ] Explicitly link to this pull request each issue that it closes
- [ ] Assign one and ideally two reviewers to review this pull request. 
- [ ] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

2022-02-08 22:34 UTC, AHuangHe commented on src/main/java/edu/ucsb/cs156/team02/controllers/UCSBSubjectController.java
>  /*
Try uncommenting this for the test?

2022-02-08 22:50 UTC, AHuangHe approved these changes
LGTM

2022-02-08 22:58 UTC, AHuangHe requested changes
Needs an additional test case

2022-02-08 22:58 UTC, AHuangHe commented on src/test/java/edu/ucsb/cs156/team02/controllers/UCSBSubjectControllerTests.java
> +
Oh, I think you are missing the test case where the user wants to delete a subject that does not exist

2022-02-09 01:13 UTC, edisonnchen approved these changes
LGTM

2022-02-09 01:44 UTC, merged